name = "nimbus-store"
main = "src/index.js"
compatibility_date = "2024-11-01"

# ---------- static assets ----------
[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

# ---------- D1 database ----------
# Replace database_id with the value printed by:
#   npx wrangler d1 create nimbus-db
[[d1_databases]]
binding = "DB"
database_name = "nimbus-db"
database_id = "5887518f-9433-4e85-a78b-e8620c5ece03"

# ---------- environment ----------
[vars]
ADMIN_PASSWORD = "06142014Aa@"
